### ISSUE TITLE
Close scores inflated

### ISSUE THREAD

**Issue by Correy27** [dtcarls/fantasy_football_chat_bot#45] opened 2019-09-09 23:25 UTC
One of the "close scores" is showing an incorrect score.

> Close Scores
> TEAM 111.56 - 114.40 PUTY
> DUCK 72.54 - 85.56 NATE

The first score for TEAM shows 111.56 but the actual score for that team is 102.6. They have no one else playing tonight so their projected score also shows 102.6. Not sure where 111.56 is coming from, no team has that score.

Re-deployed the latest bot on Friday for Discord.

**Comment by dtcarls** [comment] 2019-09-09 23:37
This will be very difficult to troubleshoot while a game is in progress. Can you provide your league id. If your league is not public please provide a screenshot of the full lineups (with bench) of the teams that have reported and inflated score and the incorrect corresponding message.

**Comment by dtcarls** [comment] 2019-09-09 23:40
Closing this as a duplicate of https://github.com/dtcarls/fantasy_football_chat_bot/issues/44

**Closed by dtcarls** 2019-09-09 23:40 UTC
