### ISSUE TITLE
Actual Score Update -- Friday AM Shows LW

### ISSUE THREAD

**Issue by Carbja23** [dtcarls/fantasy_football_chat_bot#48] opened 2019-09-13 11:32 UTC
**Describe the bug**
Actual Score Update (7:30AM EST) update is last week's scores.

**Expected behavior**
Should show only scores from the Thursday Night Game

**Comment by bs0l** [comment] 2019-09-13 12:35
Having the same issue

**Comment by HennDev** [comment] 2019-09-13 12:42
I'm seeing the same thing. I think this is related to the get_current_week() function, I think like 102ish. 


Since it's only look at a single team's score, if that team doesn't have anyone on Thursday, it deduces nobody has a score and it's a "future week".

**Comment by dtcarls** [comment] 2019-09-13 12:43
Thinking the same thing. Not sure why it would've worked last year. Working
to fix.

**Comment by HennDev** [comment] 2019-09-13 12:47
I blame ESPNs horrible design!

**Comment by foobartles** [comment] 2019-09-13 13:45
https://github.com/dtcarls/fantasy_football_chat_bot/issues/47 

I imagine this issue is also being caused by the same thing. I think the problem code is coming from the league.scoreboard() call

**Comment by ZachMyers3** [comment] 2019-09-13 14:07
Submitted a PR to fix the issue [#49](https://github.com/dtcarls/fantasy_football_chat_bot/pull/49).

**Comment by dtcarls** [comment] 2019-09-13 15:39
Potentially fixed with latest merges. Leaving ticket open for a week for verification

**Comment by nez-the-old** [comment] 2019-09-13 16:26
dtcarls your merge fix filter down to us peons automatically or do we have to reinstall the bot?

**Comment by dtcarls** [comment] 2019-09-13 16:29
Unfortunately you have to reinstall. A lot of bugs this year with the new
API and even bugs with ESPNs data. Hopefully this is the last of the major
ones.

**Comment by nez-the-old** [comment] 2019-09-13 16:57
Hey man no worries! I appreciate you supporting this fun bot!

**Comment by dtcarls** [comment] 2019-09-16 14:51
Closing issue as it didn't occur over the weekend with latest version. Reopen if problem re-occurs

**Closed by dtcarls** 2019-09-16 14:51 UTC
